---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS) 
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

  - name: create splunkuser service account
    tags: always
    user:
      name: splunkuser 
      groups: wheel 

  - name: add ssh key for splunkuser
    tags: always
    authorized_key:
      user: splunkuser
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOQ3p391P2eBsedN0hIQMZF/wvpDBjDwFODOI7ZSL44h ansible"  

  - name: add sudoers file for splunkuser
    tags: always
    copy:
      src: sudoer_splunkuser
      dest: /etc/sudoers.d/splunkuser
      owner: root
      group: root
      mode: 0440

  - name: install unzip
    package:
      name: unzip
 
 
  - name: install updates (Ubuntu) 
    tags: always
    apt:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS) 
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


