---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
        - vim
        - net-tools
        - yum-utils
        - wget
        - epel-release
        - python3-pexpect.noarch
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

